version: '3.4'
services:
    judgehost:
#        build: ./judgehost
        image: domjudge/judgehost-extended:8.0.0 #Needs manual build through build.sh in ./judgehost
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
        hostname: judgehost
        env_file:
            - judgehost.env
