version: "3"

services:
  cds:
    image: icpctools/cds:2.5.751
    ports:
      - "8083:8080"
      - "8443:8443"
    volumes:
      - ${PWD}/cds/config:/opt/wlp/usr/servers/cds/config
      - ${PWD}/cds/contest:/contest
